data <- read.csv('gt_2011.csv')
data1 <- read.csv('gt_2012.csv')
data2 <- read.csv('gt_2013.csv')
data3 <- read.csv('gt_2014.csv')
data4 <- read.csv('gt_2015.csv')
train <- rbind(data,data1,data2)
test <- rbind(data3,data4)
write.csv(train,'train.csv')
write.csv(test,'test.csv')
