# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param x original data.frame
#' @param W total weight
#' @return same answer as slow mode
FastDynamicProgramming <- function(x, W) {
    .Call(`_LAB6_FastDynamicProgramming`, x, W)
}

